title: Sumanth Palla 
author: sumanthpalla
email: sumanthpalla31@gmail.com | sumanthpalla@iitkgp.ac.in
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Hi there,
          Glad you are here! By the way, I'm Sumanth, a fourth year undergraduate at IIT Kharagpur. Go have a look at my projects! 
          Don't forget me to connect on github and twitter (if possible! on LinkedIn too :) )
# social links
twitter_username: im_sumanth
github_username:  sumanthpalla

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
